### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by chyczcool** [domq/homebrew-gdb#6]
~ ❯ brew install --build-from-source domq/gdb/gdb                                                                                                                        20:23:19
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Fetching domq/gdb/gdb
==> Downloading https://ftp.gnu.org/gnu/gdb/gdb-13.1.tar.xz
Already downloaded: /Users/chyczcool/Library/Caches/Homebrew/downloads/ef16debf5280900643698d8f3dd4c76fe4628f82af1ec8ddb7ff27b675f26652--gdb-13.1.tar.xz
==> Installing gdb from domq/gdb
==> Patching
==> ../configure --enable-targets=all --prefix=/usr/local/Cellar/gdb/13.1_1 --disable-debug --disable-dependency-tracking --with-lzma --with-python=/usr/local/opt/python@3.11/bin
==> make
Last 15 lines from /Users/chyczcool/Library/Logs/Homebrew/gdb/02.make:
../../gdb/../gdbsupport/enum-flags.h:95:52: error: integer value -1 is outside the valid range of values [0, 1] for the enumeration type 'btrace_insn_flag' [-Wenum-constexpr-conversion]
../../gdb/../gdbsupport/enum-flags.h:95:52: error: integer value -1 is outside the valid range of values [0, 3] for the enumeration type 'btrace_function_flag' [-Wenum-constexpr-conversion]
In file included from ../../gdb/aarch64-tdep.c:21:
In file included from ../../gdb/defs.h:65:
../../gdb/../gdbsupport/enum-flags.h:95:52: error: integer value -1 is outside the valid range of values [0, 15] for the enumeration type 'ui_out_flag' [-Wenum-constexpr-conversion]
   95 |     integer_for_size<sizeof (T), static_cast<bool>(T (-1) < T (0))>::type
      |                                                    ^
../../gdb/../gdbsupport/enum-flags.h:95:52: error: integer value -1 is outside the valid range of values [0, 1] for the enumeration type 'btrace_insn_flag' [-Wenum-constexpr-conversion]
../../gdb/../gdbsupport/enum-flags.h:95:52: error: integer value -1 is outside the valid range of values [0, 3] for the enumeration type 'btrace_function_flag' [-Wenum-constexpr-conversion]
3 errors generated.
make[2]: *** [aarch64-ravenscar-thread.o] Error 1
3 errors generated.
make[2]: *** [aarch64-tdep.o] Error 1
make[1]: *** [all-gdb] Error 2
make: *** [all] Error 2

**Comment by domq** [comment]
Hi, I don't own a Mac with a M1 or M2 chip unfortunately, so I'm unable to
look into this error of yours.

Thanks for your understanding,

-- 
Dominique Quatravaux
***@***.***

**Comment by chyczcool** [comment]
Okay, thank you for your reply
